# Generated by Django 4.0.4 on 2022-05-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_show_accessible_seating_show_seating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='headliner',
            field=models.BooleanField(default=False),
        ),
    ]
