# Generated by Django 4.0.4 on 2022-05-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seating', models.IntegerField()),
                ('accessible_seating', models.IntegerField()),
                ('image', models.CharField(max_length=8192)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.location')),
            ],
        ),
    ]
